// ==========================================
// ERASED CENTURY — SITE DATA
// ==========================================
// Auto-generated by sync.js on 2026-03-10T20:44:38.922Z
// Edit sources manually, everything else syncs from YouTube.
// Push to GitHub and the site updates automatically.
// ==========================================

const SITE_DATA = {
  "recaptcha_site_key": "6LcgRYYsAAAAAMo7p9Vc6T7mFGptBtFtiM5kgI78",
  "beehiiv_magic_link": "https://magic.beehiiv.com/v1/1ff062b4-35b2-4de9-930d-82c8a6939bbe",
  "channel": {
    "name": "Erased Century",
    "tagline": "Hidden History, Uncovered",
    "description": "Investigating the forgotten, suppressed, and deliberately hidden chapters of human history — built on evidence, sources, and impossible archival photography.",
    "youtube_url": "https://www.youtube.com/channel/UCbbeQCNpFiblWYm3tb4PNZA",
    "subscribe_url": "https://www.youtube.com/channel/UCbbeQCNpFiblWYm3tb4PNZA?sub_confirmation=1",
    "contact_email": "erasedcentury@gmail.com",
    "subscribers": "39.4K",
    "documentaries": 41,
    "total_views": "2.3M+",
    "established": 2024
  },
  "about": {
    "quote": "I wasn't looking for any of this.",
    "paragraphs": [
      "I was researching architectural anomalies — oversized doors, impossible stonework, buildings that didn't match their supposed era — when I started finding threads that pulled me deeper into forgotten history.",
      "Erased Century is a documentary research channel built on a simple principle: every claim gets sourced, every image is intentionally crafted, and every video is designed to help you fall asleep — and maybe wake up wondering what else they didn't teach you.",
      "All research is original. All sources are cited. This isn't entertainment — it's investigation."
    ],
    "signature": "— Erased Century / Bold Core Media LLC"
  },
  "videos": [
    {
      "id": 1,
      "youtube_id": "-EXcGaC6J90",
      "title": "The Frequency They Erased From Every Violin — And Why Music Hasn't Sounded Right Since 1939",
      "date": "Mar 10, 2026",
      "duration": "15:46",
      "views": "2.7K",
      "description": "A440, 432 Hz, Verdi tuning, the 1939 London pitch conference, and the loss of local musical standards all converge in one overlooked history of modern sound. This documentary examines how A=440 became the international reference pitch, how earlier systems like France’s diapason normal and scientific",
      "thumbnail": "",
      "sources": []
    },
    {
      "id": 2,
      "youtube_id": "XTngt-jnoN8",
      "title": "In 536 AD, The World Went Dark for 18 Months — They Buried It From Every History Book",
      "date": "Mar 9, 2026",
      "duration": "16:02",
      "views": "20.1K",
      "description": "In 536 AD, the sun vanished. Volcanic ash blocked the sky, temperatures collapsed, and a 124-year climate catastrophe erased civilizations on four continents. This is the worst year in human history, and most people have never heard of it. The Dark Ages weren't vague. They had a start date, a cause,",
      "thumbnail": "",
      "sources": []
    },
    {
      "id": 3,
      "youtube_id": "-hshKJl1BTM",
      "title": "Why 43 Million Americans Suddenly Had to Prove They Were Born",
      "date": "Mar 8, 2026",
      "duration": "14:59",
      "views": "8.5K",
      "description": "Birth certificates, the 1890 census fire, Social Security numbers, Ellis Island name changes, and the disappearance of pre-registration identity all point to one unsettling question: how did America become a nation where millions of native-born citizens could not prove they existed? This documentary",
      "thumbnail": "",
      "sources": []
    },
    {
      "id": 4,
      "youtube_id": "2hHOaMJ6AZc",
      "title": "The Giant Children They Took From Orphanages and Sold to the Circus",
      "date": "Mar 7, 2026",
      "duration": "14:56",
      "views": "3.7K",
      "description": "Frederick Kempster, Barnardo’s orphanage, Home Children, orphan trains, and circus giants collide in one of the darkest forgotten stories of Victorian child migration. This documentary explores how vulnerable children were shipped overseas, exploited for labor, and in some cases turned into public s",
      "thumbnail": "",
      "sources": []
    },
    {
      "id": 5,
      "youtube_id": "k7UOqLTEmpg",
      "title": "74 Boys Were Fed Radiation for Breakfast — Then Labeled \"Morons\" So No One Would Believe Them",
      "date": "Mar 6, 2026",
      "duration": "15:12",
      "views": "17.4K",
      "description": "Fernald State School. Radioactive oatmeal. MIT’s “Science Club.” Quaker Oats funding. U.S. Atomic Energy Commission isotopes. This episode follows Fred Boyce and the Fernald experiments that turned institutionalized kids into test subjects, and traces how it fit into America’s wider human radiation ",
      "thumbnail": "",
      "sources": []
    },
    {
      "id": 6,
      "youtube_id": "vcA8SHmphfw",
      "title": "A 124 Year Bulb They Made Sure No One Could Ever Build Again",
      "date": "Mar 5, 2026",
      "duration": "15:25",
      "views": "7.5K",
      "description": "A “1000-hour light bulb” was not an accident. It was a choice. This episode tracks the Centennial Light in Livermore, California (burning since 1901) back to Adolphe Chaillet, GE’s takeover web, and the Phoebus Cartel that standardized failure. If you follow Tartaria-style “erased history,” suppress",
      "thumbnail": "",
      "sources": []
    },
    {
      "id": 7,
      "youtube_id": "zqxO4ACtt9c",
      "title": "America’s Land Map Has a “Haunting” in It (1910 Paper Trail)",
      "date": "Mar 4, 2026",
      "duration": "15:52",
      "views": "10.9K",
      "description": "There’s a circular in the National Archives most rural landowners have never heard of. Dated June 1, 1909, filed under the General Land Office, it’s titled “Restoration of Lost or Obliterated Corners.” County surveyors were reporting something chilling: original boundary monuments were gone. Not wea",
      "thumbnail": "",
      "sources": []
    },
    {
      "id": 8,
      "youtube_id": "0dMMgGrfx3Y",
      "title": "What Kind of “School” Has a Cemetery? The Carlisle Story They Never Taught You",
      "date": "Mar 3, 2026",
      "duration": "15:17",
      "views": "6K",
      "description": "Carlisle Indian Industrial School. Native American boarding schools. Forced assimilation. Renaming children. Cemeteries on campus. This episode connects the boarding school system to land seizure under the Dawes Act, missing records, and the genealogy wall families still hit today.",
      "thumbnail": "",
      "sources": []
    },
    {
      "id": 9,
      "youtube_id": "Y4cOa1KKzy0",
      "title": "America Had a System That Turned Living People Into Missing People",
      "date": "Mar 2, 2026",
      "duration": "15:43",
      "views": "31K",
      "description": "Unmarked graves. Poor farms. Almshouses. Potter’s fields. Across the U.S., parks, schools, and even golf courses were built over cemeteries for people the system classified as “paupers.” This episode connects the evidence trail from Atlanta’s Chastain Park to Chicago’s Dunning and beyond.",
      "thumbnail": "",
      "sources": []
    },
    {
      "id": 10,
      "youtube_id": "uDuQo63GHGI",
      "title": "The Frequency They Changed — And Why Everything Sounds Wrong",
      "date": "Mar 1, 2026",
      "duration": "16:02",
      "views": "328.5K",
      "description": "Beethoven’s tuning fork (A=455.4 Hz) proves A440 was not “natural” but chosen. From France’s 1859 diapason normal (A=435) to Verdi’s 432 Hz appeal, then the mass destruction of Europe’s bells, this is the hidden story of how local pitch died and cathedrals were left as unplayed instruments.",
      "thumbnail": "",
      "sources": []
    },
    {
      "id": 11,
      "youtube_id": "2DfUjc7eb8U",
      "title": "The First Movie Ever Made Was About Babies Growing in a Garden 1896 Story",
      "date": "Mar 1, 2026",
      "duration": "15:57",
      "views": "183.3K",
      "description": "If you've seen \"cabbage patch babies\" as cute folklore, this will change how you see it. This episode traces the real history behind the imagery: early cinema, incubator baby exhibitions, foundling wheels, and the orphan trains, then asks why the same visual keeps repeating for 800 years.",
      "thumbnail": "",
      "sources": []
    },
    {
      "id": 12,
      "youtube_id": "bsya8bTlNSU",
      "title": "The Pope Who Literally Ate 200 Years and Made the World Forget They Existed",
      "date": "Feb 28, 2026",
      "duration": "16:43",
      "views": "13.8K",
      "description": "Every April 6, the UK’s tax year begins, and 67 million people step into a new financial calendar that does not start on January 1. It starts on a date that only makes sense if you know what happened in September 1752.",
      "thumbnail": "",
      "sources": []
    },
    {
      "id": 13,
      "youtube_id": "7P54aeWneY8",
      "title": "A Declassified CIA Document Says the History of Tartaria Was Deliberately Falsified",
      "date": "Feb 28, 2026",
      "duration": "18:29",
      "views": "69.5K",
      "description": "If you’ve gone down the Tartaria rabbit hole, this is the source to start with: a declassified CIA Reading Room report from 1957 that documents how Soviet authorities ordered the rewriting of Tartar history, including the withdrawal and destruction of “truthful” accounts, and it explains the mechani",
      "thumbnail": "",
      "sources": []
    },
    {
      "id": 14,
      "youtube_id": "tJN6IuTF2r4",
      "title": "A Woman Disagreed With Her Husband in 1860 — She Didn't Come Home for Three Years",
      "date": "Feb 27, 2026",
      "duration": "15:14",
      "views": "5.8K",
      "description": "If you follow hidden history, erased records, and “Tartaria-style” rabbit holes, start here: the Homestead Act, railroad land grants, the Morrill Act, the Dawes Act, and the vanished 1890 census read like one connected ledger, not separate trivia.",
      "thumbnail": "",
      "sources": []
    },
    {
      "id": 15,
      "youtube_id": "xzEcPVKNrkQ",
      "title": "90% of Orphanage Children Had Living Parents — So Why Were They There?",
      "date": "Feb 26, 2026",
      "duration": "16:20",
      "views": "14.7K",
      "description": "Orphan trains, Children’s Aid Society, New York Juvenile Asylum, indenture pipeline, faith-based placement, sealed records, genealogy walls — if your family tree stops in 1890, it might not be an accident. It might be a system.",
      "thumbnail": "",
      "sources": []
    },
    {
      "id": 16,
      "youtube_id": "Ziuvezvo60Q",
      "title": "They Stole $57 Million From Freed Slaves — Then Made Frederick Douglass Take the Blame",
      "date": "Feb 25, 2026",
      "duration": "15:45",
      "views": "6K",
      "description": "Federal Writers' Project | 2,900 Lost Interviews | Why America's Transition-Era Records Keep Disappearing (1871–1940)",
      "thumbnail": "",
      "sources": []
    },
    {
      "id": 17,
      "youtube_id": "VwCZQVSzu8I",
      "title": "500 Million Acres — The Biggest Land Grab in History Was Disguised as a Gift",
      "date": "Feb 24, 2026",
      "duration": "16:19",
      "views": "52.7K",
      "description": "If you follow Tartaria-style rabbit holes, hidden history, and erased records, start here: the Homestead Act, railroad land grants, the Dawes Act, and the vanished 1890 census read like one connected ledger, not separate trivia.",
      "thumbnail": "",
      "sources": []
    },
    {
      "id": 18,
      "youtube_id": "CIIYCR8olXI",
      "title": "They Put Living Babies on Display at the World's Fair — And Nobody Asked Where They Came From",
      "date": "Feb 23, 2026",
      "duration": "15:47",
      "views": "108.4K",
      "description": "Coney Island incubator exhibit, Dr. Martin Couney, early premature infant care, World’s Fairs, boardwalk medicine, Better Babies contests, orphan trains, missing records — why were fragile newborns kept alive in glass on the midway?",
      "thumbnail": "",
      "sources": []
    },
    {
      "id": 19,
      "youtube_id": "25QVf-zPNlo",
      "title": "How Men Could Erase Their Wives Overnight — One Signature, No Hearing",
      "date": "Feb 22, 2026",
      "duration": "16:21",
      "views": "26.5K",
      "description": "Elizabeth Packard, coverture, asylum commitments, and the 1870 census wall: how did “marriage law” let husbands erase wives in 1860s America with a single signature, then keep the house, the money, and the children?",
      "thumbnail": "",
      "sources": []
    },
    {
      "id": 20,
      "youtube_id": "XVopg6F5TgY",
      "title": "The Island Where Everyone Spoke a Secret Language — Until Alexander Graham Bell Found Them",
      "date": "Feb 21, 2026",
      "duration": "12:39",
      "views": "20.3K",
      "description": "For two hundred years, something almost impossible thrived on a small island off Massachusetts. In parts of Martha's Vineyard, hereditary deafness ran so deep that in some areas one in four residents could not hear. Fishermen signed to each other from their boats. Children signed behind their teache",
      "thumbnail": "",
      "sources": []
    }
  ]
};
