// ==========================================
// ERASED CENTURY — SITE DATA
// ==========================================
// Auto-generated by sync.js on 2026-04-05T20:56:35.841Z
// Edit sources manually, everything else syncs from YouTube.
// Push to GitHub and the site updates automatically.
// ==========================================

const SITE_DATA = {
  "recaptcha_site_key": "6LcgRYYsAAAAAMo7p9Vc6T7mFGptBtFtiM5kgI78",
  "beehiiv_magic_link": "https://magic.beehiiv.com/v1/1ff062b4-35b2-4de9-930d-82c8a6939bbe",
  "channel": {
    "name": "Erased Century",
    "tagline": "Hidden History, Uncovered",
    "description": "Investigating the forgotten, suppressed, and deliberately hidden chapters of human history — built on evidence, sources, and impossible archival photography.",
    "youtube_url": "https://www.youtube.com/channel/UCbbeQCNpFiblWYm3tb4PNZA",
    "subscribe_url": "https://www.youtube.com/channel/UCbbeQCNpFiblWYm3tb4PNZA?sub_confirmation=1",
    "contact_email": "erasedcentury@gmail.com",
    "subscribers": "56.2K",
    "documentaries": 66,
    "total_views": "3.6M+",
    "established": 2024,
    "company": "Bold Core Media LLC"
  },
  "about": {
    "quote": "I wasn't looking for any of this.",
    "paragraphs": [
      "I was researching architectural anomalies — oversized doors, impossible stonework, buildings that didn't match their supposed era — when I started finding threads that pulled me deeper into forgotten history.",
      "Erased Century is a documentary research channel built on a simple principle: every claim gets sourced, every image is intentionally crafted, and every video is designed to help you fall asleep — and maybe wake up wondering what else they didn't teach you.",
      "All research is original. All sources are cited. This isn't entertainment — it's investigation."
    ],
    "signature": "— Erased Century / Bold Core Media LLC"
  },
  "videos": [
    {
      "id": 1,
      "youtube_id": "isH0dBcyG-M",
      "slug": "your-income-tax-wasnt-needed-america-proved-that-for-28-cons",
      "title": "Your Income Tax Wasn't Needed — America Proved That for 28 Consecutive Years",
      "date": "Apr 5, 2026",
      "duration": "15:20",
      "views": "767",
      "description": "James Tanner, the federal surplus, Civil War pensions, the Billion Dollar Congress, the Panic of 1893, and the rise of modern American debt all collide in this documentary about the moment the United States stopped trying to pay off what it owed and began building the fiscal architecture that would ",
      "thumbnail": "",
      "sources": []
    },
    {
      "id": 2,
      "youtube_id": "8WURL9gY1cg",
      "slug": "the-day-america-changed-forever-323-days-nobody-will-teach-y",
      "title": "The Day America Changed Forever — 323 Days Nobody Will Teach You About",
      "date": "Apr 4, 2026",
      "duration": "15:35",
      "views": "2.7K",
      "description": "Sixteenth Amendment, Seventeenth Amendment, federal income tax, direct election of senators, federal grants, state sovereignty, fiscal dependence, and 1913 all collide in this documentary about the single year that rewired how American states fund themselves, how they influence Washington, and how m",
      "thumbnail": "",
      "sources": []
    },
    {
      "id": 3,
      "youtube_id": "FNzFv9tyeUU",
      "slug": "every-time-america-was-about-to-learn-the-truth-a-building-c",
      "title": "Every Time America Was About to Learn the Truth, a Building Caught Fire",
      "date": "Apr 3, 2026",
      "duration": "15:23",
      "views": "2.9K",
      "description": "Ellis Island, the lost 1890 census, courthouse fires, Black land loss, and the 1973 National Personnel Records Center fire all collide in this documentary about what happens when a country keeps losing the records people need to prove who they are, what they owned, and what they earned.",
      "thumbnail": "",
      "sources": []
    },
    {
      "id": 4,
      "youtube_id": "1iAYqIM7BrI",
      "slug": "what-america-puts-in-its-water-was-illegal-in-1939-then-they",
      "title": "What America Puts in Its Water Was Illegal in 1939 — Then They Made You Drink It",
      "date": "Apr 2, 2026",
      "duration": "15:59",
      "views": "2.8K",
      "description": "Fluoride, community water fluoridation, hexafluorosilicic acid, Grand Rapids, ALCOA, the Public Health Service, Europe’s different fluoride policies, and the 2024 federal fluoride ruling all collide in this documentary about how a chemical linked to cavity prevention also became one of the longest-r",
      "thumbnail": "",
      "sources": []
    },
    {
      "id": 5,
      "youtube_id": "PDtlNexDwTU",
      "slug": "maps-dont-show-reality-they-show-who-is-in-power",
      "title": "Maps Don’t Show Reality — They Show who is in Power",
      "date": "Apr 1, 2026",
      "duration": "17:17",
      "views": "3K",
      "description": "Terra Australis, the Piri Reis map, Bermeja, Antarctica, phantom islands, old maps, cartography, and the Antarctic Treaty all collide in this documentary about why historical maps so often showed more land than the world we are allowed to see now.",
      "thumbnail": "",
      "sources": []
    },
    {
      "id": 6,
      "youtube_id": "gHGnySAxJIc",
      "slug": "the-sky-moves-one-degree-every-72-years-thats-why-they-destr",
      "title": "The Sky Moves One Degree Every 72 Years — That's Why They Destroyed the Records",
      "date": "Mar 31, 2026",
      "duration": "16:16",
      "views": "3.9K",
      "description": "Hipparchus, the Dendera Zodiac, precession of the equinoxes, lost star catalogs, ancient astronomy, Halley’s Comet, pyramid alignment, and China’s Star Manual of Master Shi all collide in this documentary about the sky as a timestamp and the ancient records that preserved it.",
      "thumbnail": "",
      "sources": []
    },
    {
      "id": 7,
      "youtube_id": "fg1NCbV8jq8",
      "slug": "they-pull-10-million-teeth-a-year-dark-secret-of-dental-indu",
      "title": "They Pull 10 Million Teeth a Year — Dark Secret of Dental Industry",
      "date": "Mar 30, 2026",
      "duration": "16:16",
      "views": "6.2K",
      "description": "House crowding, wisdom teeth extraction, crooked teeth, the jaw epidemic, agriculture, processed food, Weston A. Price, Daniel Lieberman, Janet Monge, and the hidden history of human jaws all collide in this documentary about why ancient skulls had room for every tooth and why modern mouths so often",
      "thumbnail": "",
      "sources": []
    },
    {
      "id": 8,
      "youtube_id": "OR1fEEWbyWE",
      "slug": "your-2am-insomnia-isnt-a-disorder-they-just-made-you-the-lab",
      "title": "Your 2AM Insomnia Isn't a Disorder — They Just Made You the Lab Rat",
      "date": "Mar 29, 2026",
      "duration": "15:12",
      "views": "10.2K",
      "description": "Most people are taught a simple story: healthy sleep means one unbroken block of rest, and waking in the middle of the night means something has gone wrong. But the historical record points to a very different past. Across centuries of literature, court testimony, medical writing, and social observa",
      "thumbnail": "",
      "sources": []
    },
    {
      "id": 9,
      "youtube_id": "g_1p_WQmxcs",
      "slug": "1770-was-the-year-homes-stopped-being-private",
      "title": "1770 Was the Year Homes Stopped Being Private",
      "date": "Mar 28, 2026",
      "duration": "15:03",
      "views": "6K",
      "description": "House numbers did not begin as a convenience. This documentary explores the hidden history of addresses, house numbering, Maria Theresa’s 1770 Conscription of Souls, Prague, Prussia, Paris, military conscription, census control, genealogy dead ends, and the deeper pattern of how the modern address w",
      "thumbnail": "",
      "sources": []
    },
    {
      "id": 10,
      "youtube_id": "BK8lPA4MG8w",
      "slug": "in-1907-workers-found-a-30-foot-skull-beneath-the-town",
      "title": "In 1907, Workers Found a 30-Foot Skull Beneath the Town",
      "date": "Mar 27, 2026",
      "duration": "15:38",
      "views": "5.4K",
      "description": "Native American remains, NAGPRA, Kennewick Man, Slack Farm, museum collections, burial looting, and the Don Miller artifact case all collide in this documentary about how human remains were taken, stored, studied, trafficked, and delayed from return long after the law was supposed to stop it.",
      "thumbnail": "",
      "sources": []
    },
    {
      "id": 11,
      "youtube_id": "L9wASKNqMa0",
      "slug": "they-called-the-healers-witches-then-replaced-them-with-lice",
      "title": "They Called the Healers Witches — Then Replaced Them With Licensed Men",
      "date": "Mar 26, 2026",
      "duration": "16:23",
      "views": "6K",
      "description": "Hospitals did not begin with Benjamin Franklin. This documentary explores ancient Greek Asclepieia, Islamic bimaristans, Ottoman music therapy, Henry VIII’s destruction of English hospitals, the Flexner Report, and the deeper pattern of how free healing systems were dismantled, centralized, and rewr",
      "thumbnail": "",
      "sources": []
    },
    {
      "id": 12,
      "youtube_id": "qYZpnHK_yNw",
      "slug": "476-ad-the-purple-snail-behind-the-death-of-imperial-rome",
      "title": "476 AD — The Purple Snail Behind the Death of Imperial Rome",
      "date": "Mar 24, 2026",
      "duration": "16:37",
      "views": "19.8K",
      "description": "The Color They Removed From Every Flag After 1900 explores purple flags, Tyrian purple, William Henry Perkin, mauveine, the Spanish Second Republic, the Dutch Prince’s Flag, and the deeper history of why purple became one of the rarest colors in modern national symbolism.",
      "thumbnail": "",
      "sources": []
    },
    {
      "id": 13,
      "youtube_id": "UWdY8U9IDYo",
      "slug": "they-harvested-antarctica-before-1820-then-sealed-it",
      "title": "They Harvested Antarctica Before 1820 — Then Sealed It",
      "date": "Mar 23, 2026",
      "duration": "15:36",
      "views": "36.9K",
      "description": "Antarctica conspiracy theories, the Piri Reis map, Operation Highjump, the Antarctic Treaty, Tartaria, and the oldest Antarctic ice core all collide in this documentary about what the historical record really says. We trace the real story behind ancient map claims, secret-history theories, buried ci",
      "thumbnail": "",
      "sources": []
    },
    {
      "id": 14,
      "youtube_id": "LUaeY6N-bpQ",
      "slug": "they-didnt-just-change-the-name-they-broke-the-family-line",
      "title": "They Didn’t Just Change the Name — They Broke the Family Line",
      "date": "Mar 22, 2026",
      "duration": "15:28",
      "views": "11.7K",
      "description": "Your last name may not be the name your family carried when they arrived in America. This documentary explores the Ellis Island name change myth, Jewish surname changes, German American erasure during World War I, Native American boarding schools, slavery-era census gaps, and the destroyed 1890 cens",
      "thumbnail": "",
      "sources": []
    },
    {
      "id": 15,
      "youtube_id": "HfybJUl9XaY",
      "slug": "she-remembers-being-called-a-tartar-she-doesnt-know-what-it-",
      "title": "She Remembers Being Called a Tartar — She Doesn't Know What It Means",
      "date": "Mar 21, 2026",
      "duration": "15:36",
      "views": "28.4K",
      "description": "Tartary. Tartaria. Tatars. Tatarstan. A word that once covered huge stretches of Asia on Western maps is now so forgotten that many people assume it was invented by the internet. This episode follows the disappearance of Tartary from maps, encyclopedias, travel books, and finally family memory itsel",
      "thumbnail": "",
      "sources": []
    },
    {
      "id": 16,
      "youtube_id": "LMljX1RscJY",
      "slug": "the-year-your-paycheck-stopped-belonging-to-your-family",
      "title": "The Year Your Paycheck Stopped Belonging to Your Family",
      "date": "Mar 20, 2026",
      "duration": "15:15",
      "views": "36.2K",
      "description": "1913 changed America forever. The Federal Reserve. The federal income tax. The direct election of senators. In just ten months, three structural changes rewired how money, power, and representation worked in the United States. This episode follows the documented story behind that transformation — fr",
      "thumbnail": "",
      "sources": []
    },
    {
      "id": 17,
      "youtube_id": "_TFAWenB894",
      "slug": "they-found-the-workers-still-standing-frozen-upright-with-sh",
      "title": "They Found the Workers Still Standing — Frozen Upright With Shovels in Their Hands",
      "date": "Mar 19, 2026",
      "duration": "16:13",
      "views": "49.1K",
      "description": "The Giants Who Built the Railroads. Ten Miles in One Day. 12,000 Chinese laborers. Missing names, missing records, and photographs that never seem to tell the full story. This episode follows the workers who built the western half of the transcontinental railroad, the impossible engineering feats th",
      "thumbnail": "",
      "sources": []
    },
    {
      "id": 18,
      "youtube_id": "P0628zEUz5w",
      "slug": "they-deleted-your-grandmothers-real-birthday-the-calendar-re",
      "title": "They Deleted Your Grandmother's Real Birthday — The Calendar Reset of 1582",
      "date": "Mar 18, 2026",
      "duration": "15:49",
      "views": "11.1K",
      "description": "The 1890 census was destroyed. Formerly enslaved people were not recorded by name until 1870. Native children were renamed in boarding schools. Immigrant names were often altered long after arrival, not at Ellis Island. This documentary explores lost census records, erased surnames, genealogy gaps, ",
      "thumbnail": "",
      "sources": []
    },
    {
      "id": 19,
      "youtube_id": "NmI8JMRV_5M",
      "slug": "they-sorted-children-by-what-their-bodies-could-do",
      "title": "They Sorted Children by What Their Bodies Could Do",
      "date": "Mar 17, 2026",
      "duration": "14:59",
      "views": "4.8K",
      "description": "The orphan train movement is remembered as a rescue mission. But what if that is only half the story? This documentary explores orphan trains, New York child relocation, dime museums, sideshows, erased identities, sealed records, and the disturbing overlap between America’s child welfare system and ",
      "thumbnail": "",
      "sources": []
    },
    {
      "id": 20,
      "youtube_id": "4jGAk8rCG7s",
      "slug": "your-blood-type-was-changed-after-1900-the-tartarian-dna-the",
      "title": "Your Blood Type Was Changed After 1900 — The Tartarian DNA They Replaced",
      "date": "Mar 16, 2026",
      "duration": "16:17",
      "views": "31.7K",
      "description": "Your blood type is not just A, B, AB, or O. This video explores the hidden history of blood type, Karl Landsteiner’s ABO discovery, the older humoral system of constitutional medicine, the Flexner Report, disease risk by blood group, Rh-negative blood, and why modern medicine may have reduced blood ",
      "thumbnail": "",
      "sources": []
    }
  ]
};
