// ==========================================
// ERASED CENTURY — SITE DATA
// ==========================================
// Auto-generated by sync.js on 2026-03-10T20:44:38.922Z
// Edit sources manually, everything else syncs from YouTube.
// Push to GitHub and the site updates automatically.
//
// SOURCE FORMAT (categorized):
//   "sources": [
//     {
//       "category": "Category Name",
//       "items": [
//         {
//           "text": "Source title or description",
//           "url": "https://...",           // optional, omit or "" for no link
//           "note": "Why this matters...",   // optional context
//           "type": "book"                   // optional: book|paper|news|archive|gov|web|video|doc
//         }
//       ]
//     }
//   ]
//
// Or flat format (still supported):
//   "sources": [{ "text": "...", "url": "..." }]
//
// Or empty (shows "Sources coming soon"):
//   "sources": []
// ==========================================

const SITE_DATA = {
  recaptcha_site_key: "6LcgRYYsAAAAAMo7p9Vc6T7mFGptBtFtiM5kgI78",
  beehiiv_magic_link:
    "https://magic.beehiiv.com/v1/1ff062b4-35b2-4de9-930d-82c8a6939bbe",
  channel: {
    name: "Erased Century",
    tagline: "Hidden History, Uncovered",
    description:
      "Investigating the forgotten, suppressed, and deliberately hidden chapters of human history — built on evidence, sources, and impossible archival photography.",
    youtube_url: "https://www.youtube.com/channel/UCbbeQCNpFiblWYm3tb4PNZA",
    subscribe_url:
      "https://www.youtube.com/channel/UCbbeQCNpFiblWYm3tb4PNZA?sub_confirmation=1",
    contact_email: "erasedcentury@gmail.com",
    subscribers: "39.4K",
    documentaries: 41,
    total_views: "2.3M+",
    established: 2024
  },
  about: {
    quote: "I wasn't looking for any of this.",
    paragraphs: [
      "I was researching architectural anomalies — oversized doors, impossible stonework, buildings that didn't match their supposed era — when I started finding threads that pulled me deeper into forgotten history.",
      "Erased Century is a documentary research channel built on a simple principle: every claim gets sourced, every image is intentionally crafted, and every video is designed to help you fall asleep — and maybe wake up wondering what else they didn't teach you.",
      "All research is original. All sources are cited. This isn't entertainment — it's investigation."
    ],
    signature: "— Erased Century / Bold Core Media LLC"
  },
  videos: [
    {
      id: 1,
      youtube_id: "-EXcGaC6J90",
      title:
        "The Frequency They Erased From Every Violin — And Why Music Hasn't Sounded Right Since 1939",
      date: "Mar 10, 2026",
      duration: "15:46",
      views: "2.7K",
      description:
        "A440, 432 Hz, Verdi tuning, the 1939 London pitch conference, and the loss of local musical standards all converge in one overlooked history of modern sound.",
      thumbnail: "",
      sources: [
        {
          category: "Primary Sources",
          items: [
            {
              text: "ISO 16:1975 — Acoustics: Standard tuning frequency",
              url: "https://www.iso.org/standard/3601.html",
              note: "The international standard that codified A=440 Hz. Still in effect.",
              type: "doc"
            },
            {
              text: "Minutes of the 1939 International Conference on Pitch, London",
              url: "",
              note: "The conference where A=440 was adopted over competing proposals including A=435 and A=432.",
              type: "archive"
            }
          ]
        },
        {
          category: "Academic Research",
          items: [
            {
              text: "Cavanagh, L. — A Brief History of the Establishment of International Standard Pitch A=440 Hz",
              url: "",
              note: "Comprehensive academic history tracing the pitch standardization debate from the 18th century forward.",
              type: "paper"
            },
            {
              text: "Haynes, B. — A History of Performing Pitch: The Story of 'A'",
              url: "",
              note: "Documents how concert pitch varied wildly across European cities, from A=380 to A=480 Hz.",
              type: "book"
            }
          ]
        },
        {
          category: "Historical Context",
          items: [
            {
              text: "Verdi's 1884 letter to the Italian Music Commission advocating A=432",
              url: "",
              note: "Giuseppe Verdi personally lobbied for A=432 Hz, calling it the 'natural' pitch for Italian opera voices.",
              type: "archive"
            },
            {
              text: "France's 1859 Diapason Normal decree establishing A=435 Hz",
              url: "",
              note: "The first government-mandated pitch standard in history, signed by Napoleon III.",
              type: "gov"
            }
          ]
        }
      ]
    },
    {
      id: 2,
      youtube_id: "XTngt-jnoN8",
      title:
        "In 536 AD, The World Went Dark for 18 Months — They Buried It From Every History Book",
      date: "Mar 9, 2026",
      duration: "16:02",
      views: "20.1K",
      description:
        "In 536 AD, the sun vanished. Volcanic ash blocked the sky, temperatures collapsed, and a 124-year climate catastrophe erased civilizations on four continents.",
      thumbnail: "",
      sources: [
        {
          category: "Primary Sources",
          items: [
            {
              text: "Procopius of Caesarea — History of the Wars, Book IV, Ch. 14",
              url: "",
              note: "Eyewitness account: 'The sun gave forth its light without brightness, like the moon, during this whole year.'",
              type: "book"
            },
            {
              text: "Cassiodorus — Variae, Letter 25 (c. 538 AD)",
              url: "",
              note: "Roman senator describes blue-colored sun, failed harvests, and snow in summer across Italy.",
              type: "archive"
            }
          ]
        },
        {
          category: "Scientific Research",
          items: [
            {
              text: "Büntgen et al. (2016) — Cooling and societal change during the Late Antique Little Ice Age, Nature Geoscience",
              url: "https://www.nature.com/articles/ngeo2652",
              note: "Ice core and tree ring analysis identifying massive volcanic eruptions in 536 and 540 AD.",
              type: "paper"
            },
            {
              text: "Gibbons, A. (2018) — Why 536 was the worst year to be alive, Science Magazine",
              url: "https://www.science.org/content/article/why-536-was-worst-year-be-alive",
              note: "Harvard-led team pinpoints an Icelandic volcano as the source of the 536 AD fog.",
              type: "news"
            },
            {
              text: "Sigl, M. et al. (2015) — Timing and climate forcing of volcanic eruptions for the past 2,500 years, Nature",
              url: "",
              note: "Alpine ice core study linking the 536 and 540 eruptions to the Late Antique Little Ice Age.",
              type: "paper"
            }
          ]
        },
        {
          category: "Further Reading",
          items: [
            {
              text: "Keys, D. — Catastrophe: An Investigation into the Origins of the Modern World",
              url: "",
              note: "Book-length investigation into how the 536 event reshaped civilizations from Rome to China.",
              type: "book"
            },
            {
              text: "Arjava, A. (2005) — The Mystery Cloud of 536 CE in the Mediterranean Sources, Dumbarton Oaks Papers",
              url: "",
              note: "Analysis of every known Mediterranean text referencing the 536 dimming event.",
              type: "paper"
            }
          ]
        }
      ]
    },
    {
      id: 3,
      youtube_id: "-hshKJl1BTM",
      title: "Why 43 Million Americans Suddenly Had to Prove They Were Born",
      date: "Mar 8, 2026",
      duration: "14:59",
      views: "8.5K",
      description:
        "Birth certificates, the 1890 census fire, Social Security numbers, Ellis Island name changes, and the disappearance of pre-registration identity.",
      thumbnail: "",
      sources: []
    },
    {
      id: 4,
      youtube_id: "2hHOaMJ6AZc",
      title:
        "The Giant Children They Took From Orphanages and Sold to the Circus",
      date: "Mar 7, 2026",
      duration: "14:56",
      views: "3.7K",
      description:
        "Frederick Kempster, Barnardo's orphanage, Home Children, orphan trains, and circus giants collide in one of the darkest forgotten stories of Victorian child migration.",
      thumbnail: "",
      sources: []
    },
    {
      id: 5,
      youtube_id: "k7UOqLTEmpg",
      title:
        '74 Boys Were Fed Radiation for Breakfast — Then Labeled "Morons" So No One Would Believe Them',
      date: "Mar 6, 2026",
      duration: "15:12",
      views: "17.4K",
      description:
        'Fernald State School. Radioactive oatmeal. MIT\'s "Science Club." Quaker Oats funding. U.S. Atomic Energy Commission isotopes.',
      thumbnail: "",
      sources: []
    },
    {
      id: 6,
      youtube_id: "vcA8SHmphfw",
      title: "A 124 Year Bulb They Made Sure No One Could Ever Build Again",
      date: "Mar 5, 2026",
      duration: "15:25",
      views: "7.5K",
      description:
        "The Centennial Light, Adolphe Chaillet, GE's takeover web, and the Phoebus Cartel that standardized failure.",
      thumbnail: "",
      sources: []
    },
    {
      id: 7,
      youtube_id: "zqxO4ACtt9c",
      title: 'America\'s Land Map Has a "Haunting" in It (1910 Paper Trail)',
      date: "Mar 4, 2026",
      duration: "15:52",
      views: "10.9K",
      description:
        'A 1909 General Land Office circular titled "Restoration of Lost or Obliterated Corners" reveals something chilling about America\'s boundary monuments.',
      thumbnail: "",
      sources: []
    },
    {
      id: 8,
      youtube_id: "0dMMgGrfx3Y",
      title:
        'What Kind of "School" Has a Cemetery? The Carlisle Story They Never Taught You',
      date: "Mar 3, 2026",
      duration: "15:17",
      views: "6K",
      description:
        "Carlisle Indian Industrial School. Native American boarding schools. Forced assimilation. Renaming children. Cemeteries on campus.",
      thumbnail: "",
      sources: []
    },
    {
      id: 9,
      youtube_id: "Y4cOa1KKzy0",
      title:
        "America Had a System That Turned Living People Into Missing People",
      date: "Mar 2, 2026",
      duration: "15:43",
      views: "31K",
      description:
        'Unmarked graves. Poor farms. Almshouses. Potter\'s fields. Parks, schools, and golf courses built over cemeteries for people the system classified as "paupers."',
      thumbnail: "",
      sources: []
    },
    {
      id: 10,
      youtube_id: "uDuQo63GHGI",
      title: "The Frequency They Changed — And Why Everything Sounds Wrong",
      date: "Mar 1, 2026",
      duration: "16:02",
      views: "328.5K",
      description:
        'Beethoven\'s tuning fork (A=455.4 Hz) proves A440 was not "natural" but chosen. The hidden story of how local pitch died and cathedrals were left as unplayed instruments.',
      thumbnail: "",
      sources: []
    },
    {
      id: 11,
      youtube_id: "2DfUjc7eb8U",
      title:
        "The First Movie Ever Made Was About Babies Growing in a Garden 1896 Story",
      date: "Mar 1, 2026",
      duration: "15:57",
      views: "183.3K",
      description:
        "Early cinema, incubator baby exhibitions, foundling wheels, and the orphan trains — why the same visual keeps repeating for 800 years.",
      thumbnail: "",
      sources: []
    },
    {
      id: 12,
      youtube_id: "bsya8bTlNSU",
      title:
        "The Pope Who Literally Ate 200 Years and Made the World Forget They Existed",
      date: "Feb 28, 2026",
      duration: "16:43",
      views: "13.8K",
      description:
        "Every April 6, the UK's tax year begins on a date that only makes sense if you know what happened in September 1752.",
      thumbnail: "",
      sources: []
    },
    {
      id: 13,
      youtube_id: "7P54aeWneY8",
      title:
        "A Declassified CIA Document Says the History of Tartaria Was Deliberately Falsified",
      date: "Feb 28, 2026",
      duration: "18:29",
      views: "69.5K",
      description:
        "A declassified CIA Reading Room report from 1957 documents how Soviet authorities ordered the rewriting of Tartar history.",
      thumbnail: "",
      sources: []
    },
    {
      id: 14,
      youtube_id: "tJN6IuTF2r4",
      title:
        "A Woman Disagreed With Her Husband in 1860 — She Didn't Come Home for Three Years",
      date: "Feb 27, 2026",
      duration: "15:14",
      views: "5.8K",
      description:
        "The Homestead Act, railroad land grants, the Morrill Act, the Dawes Act, and the vanished 1890 census.",
      thumbnail: "",
      sources: []
    },
    {
      id: 15,
      youtube_id: "xzEcPVKNrkQ",
      title:
        "90% of Orphanage Children Had Living Parents — So Why Were They There?",
      date: "Feb 26, 2026",
      duration: "16:20",
      views: "14.7K",
      description:
        "Orphan trains, Children's Aid Society, New York Juvenile Asylum, indenture pipeline, sealed records, genealogy walls.",
      thumbnail: "",
      sources: []
    },
    {
      id: 16,
      youtube_id: "Ziuvezvo60Q",
      title:
        "They Stole $57 Million From Freed Slaves — Then Made Frederick Douglass Take the Blame",
      date: "Feb 25, 2026",
      duration: "15:45",
      views: "6K",
      description:
        "Federal Writers' Project, 2,900 lost interviews, and why America's transition-era records keep disappearing.",
      thumbnail: "",
      sources: []
    },
    {
      id: 17,
      youtube_id: "VwCZQVSzu8I",
      title:
        "500 Million Acres — The Biggest Land Grab in History Was Disguised as a Gift",
      date: "Feb 24, 2026",
      duration: "16:19",
      views: "52.7K",
      description:
        "The Homestead Act, railroad land grants, the Dawes Act, and the vanished 1890 census read like one connected ledger.",
      thumbnail: "",
      sources: []
    },
    {
      id: 18,
      youtube_id: "CIIYCR8olXI",
      title:
        "They Put Living Babies on Display at the World's Fair — And Nobody Asked Where They Came From",
      date: "Feb 23, 2026",
      duration: "15:47",
      views: "108.4K",
      description:
        "Coney Island incubator exhibit, Dr. Martin Couney, early premature infant care, World's Fairs, boardwalk medicine.",
      thumbnail: "",
      sources: []
    },
    {
      id: 19,
      youtube_id: "25QVf-zPNlo",
      title:
        "How Men Could Erase Their Wives Overnight — One Signature, No Hearing",
      date: "Feb 22, 2026",
      duration: "16:21",
      views: "26.5K",
      description:
        "Elizabeth Packard, coverture, asylum commitments, and the 1870 census wall.",
      thumbnail: "",
      sources: []
    },
    {
      id: 20,
      youtube_id: "XVopg6F5TgY",
      title:
        "The Island Where Everyone Spoke a Secret Language — Until Alexander Graham Bell Found Them",
      date: "Feb 21, 2026",
      duration: "12:39",
      views: "20.3K",
      description:
        "For two hundred years, hereditary deafness on Martha's Vineyard created a community where everyone signed.",
      thumbnail: "",
      sources: []
    }
  ]
};
